import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const noto = Noto_Sans_KR({
  weight: ["400", "500", "700"],
  variable: "--font-noto",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "PEECEMAKER",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.ico",
      href: "/favicon.ico",
    },
    shortcut: '/favicon.ico',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${noto.variable} ${noto.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
